/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.web.server;

import static org.junit.Assert.assertEquals;

import java.time.Instant;
import java.time.ZoneId;
import java.util.Date;

import org.eclipse.kura.KuraErrorCode;
import org.eclipse.kura.KuraException;
import org.eclipse.kura.clock.ClockService;
import org.junit.Test;

public class GwtStatusServiceImplClockTest {

    private long epochMillis;
    private ZoneId zone;
    private ClockService clockService;
    private String result;

    @Test
    public void formatDateTimeRendersFixedOffsetZone() {
        givenEpochMillis("2024-01-15T10:00:00Z");
        givenZone("Europe/Helsinki");

        whenFormatDateTimeIsCalled();

        thenResultIs("2024-01-15 12:00:00 (UTC+02:00, Europe/Helsinki)");
    }

    @Test
    public void formatDateTimeRendersZeroOffsetAsPlusZero() {
        givenEpochMillis("2024-01-15T10:00:00Z");
        givenZone("UTC");

        whenFormatDateTimeIsCalled();

        thenResultIs("2024-01-15 10:00:00 (UTC+00:00, UTC)");
    }

    @Test
    public void formatLastSyncWithDateReturnsFormattedString() {
        givenZone("Europe/Helsinki");
        givenClockServiceReturning(Date.from(Instant.parse("2024-01-15T10:00:00Z")));

        whenFormatLastSyncIsCalled();

        thenResultIs("2024-01-15 12:00:00 (UTC+02:00, Europe/Helsinki)");
    }

    @Test
    public void formatLastSyncWithNullReturnsNeverSinceStartup() {
        givenZone("Europe/Helsinki");
        givenClockServiceReturning(null);

        whenFormatLastSyncIsCalled();

        thenResultIs("never (since startup)");
    }

    @Test
    public void formatLastSyncWithKuraExceptionReturnsSyncDisabled() {
        givenZone("Europe/Helsinki");
        givenClockServiceThrowing();

        whenFormatLastSyncIsCalled();

        thenResultIs("sync disabled");
    }

    /*
     * Given
     */

    private void givenEpochMillis(String isoInstant) {
        this.epochMillis = Instant.parse(isoInstant).toEpochMilli();
    }

    private void givenZone(String zoneId) {
        this.zone = ZoneId.of(zoneId);
    }

    private void givenClockServiceReturning(Date date) {
        this.clockService = () -> date;
    }

    private void givenClockServiceThrowing() {
        this.clockService = () -> {
            throw new KuraException(KuraErrorCode.UNAVAILABLE_DEVICE);
        };
    }

    /*
     * When
     */

    private void whenFormatDateTimeIsCalled() {
        this.result = GwtStatusServiceImpl.formatDateTime(this.epochMillis, this.zone);
    }

    private void whenFormatLastSyncIsCalled() {
        this.result = GwtStatusServiceImpl.formatLastSync(this.clockService, this.zone);
    }

    /*
     * Then
     */

    private void thenResultIs(String expected) {
        assertEquals(expected, this.result);
    }
}
