/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.web.server;

import static org.junit.Assert.assertEquals;

import java.time.Instant;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import org.eclipse.kura.KuraErrorCode;
import org.eclipse.kura.KuraException;
import org.eclipse.kura.clock.ClockService;
import org.eclipse.kura.clock.ClockSyncState;
import org.eclipse.kura.clock.ClockSyncStatus;
import org.eclipse.kura.web.shared.model.GwtGroupedNVPair;
import org.junit.Test;

public class GwtStatusServiceImplClockTest {

    private long epochMillis;
    private ZoneId zone;
    private ClockService clockService;
    private String result;
    private ClockSyncState syncState;
    private List<GwtGroupedNVPair> pairs;

    @Test
    public void formatDateTimeRendersFixedOffsetZone() {
        givenEpochMillis("2024-01-15T10:00:00Z");
        givenZone("Europe/Helsinki");

        whenFormatDateTimeIsCalled();

        thenResultIs("2024-01-15 12:00:00 (UTC+02:00, Europe/Helsinki)");
    }

    @Test
    public void formatDateTimeRendersZeroOffsetAsPlusZero() {
        givenEpochMillis("2024-01-15T10:00:00Z");
        givenZone("UTC");

        whenFormatDateTimeIsCalled();

        thenResultIs("2024-01-15 10:00:00 (UTC+00:00, UTC)");
    }

    @Test
    public void formatLastSyncWithDateReturnsFormattedString() {
        givenZone("Europe/Helsinki");
        givenClockServiceReturning(Date.from(Instant.parse("2024-01-15T10:00:00Z")));

        whenFormatLastSyncIsCalled();

        thenResultIs("2024-01-15 12:00:00 (UTC+02:00, Europe/Helsinki)");
    }

    @Test
    public void formatLastSyncWithNullReturnsNeverSinceStartup() {
        givenZone("Europe/Helsinki");
        givenClockServiceReturning(null);

        whenFormatLastSyncIsCalled();

        thenResultIs("never (since startup)");
    }

    @Test
    public void formatLastSyncWithKuraExceptionReturnsSyncDisabled() {
        givenZone("Europe/Helsinki");
        givenClockServiceThrowing();

        whenFormatLastSyncIsCalled();

        thenResultIs("sync disabled");
    }

    @Test
    public void addSyncHealthRowsWithSyncedStateAndNullProviderAppendsOnlyStatusRow() {
        givenClockServiceReturningSyncStatus(ClockSyncState.SYNCED, null);

        whenAddSyncHealthRowsIsCalled();

        thenPairsCountIs(1);
        thenPairHasGroupNameValue(0, "clockStatus", "Clock Sync Status",
                "<span id=\"status-clock-syncstatus\">synced</span>");
    }

    @Test
    public void addSyncHealthRowsWithNotSyncedStateAppendsNotSyncedStatusRow() {
        givenClockServiceReturningSyncStatus(ClockSyncState.NOT_SYNCED, null);

        whenAddSyncHealthRowsIsCalled();

        thenPairsCountIs(1);
        thenPairHasGroupNameValue(0, "clockStatus", "Clock Sync Status",
                "<span id=\"status-clock-syncstatus\">not synced</span>");
    }

    @Test
    public void addSyncHealthRowsWithUnknownStateAppendsUnknownStatusRow() {
        givenClockServiceReturningSyncStatus(ClockSyncState.UNKNOWN, null);

        whenAddSyncHealthRowsIsCalled();

        thenPairsCountIs(1);
        thenPairHasGroupNameValue(0, "clockStatus", "Clock Sync Status",
                "<span id=\"status-clock-syncstatus\">unknown</span>");
    }

    @Test
    public void addSyncHealthRowsWithNonNullProviderAppendsProviderRow() {
        givenClockServiceReturningSyncStatus(ClockSyncState.SYNCED, "java-ntp");

        whenAddSyncHealthRowsIsCalled();

        thenPairsCountIs(2);
        thenPairHasGroupNameValue(0, "clockStatus", "Clock Sync Status",
                "<span id=\"status-clock-syncstatus\">synced</span>");
        thenPairHasGroupNameValue(1, "clockStatus", "Clock Sync Provider",
                "<span id=\"status-clock-syncprovider\">java-ntp</span>");
    }

    @Test
    public void addSyncHealthRowsWithHtmlMetacharactersInProviderEscapesProviderValue() {
        givenClockServiceReturningSyncStatus(ClockSyncState.SYNCED, "a<b>&\"c");

        whenAddSyncHealthRowsIsCalled();

        thenPairsCountIs(2);
        thenPairHasGroupNameValue(1, "clockStatus", "Clock Sync Provider",
                "<span id=\"status-clock-syncprovider\">a&lt;b&gt;&amp;&quot;c</span>");
    }

    @Test
    public void addSyncHealthRowsWithKuraExceptionAppendsSyncDisabledRowOnly() {
        givenClockServiceSyncStatusThrowing();

        whenAddSyncHealthRowsIsCalled();

        thenPairsCountIs(1);
        thenPairHasGroupNameValue(0, "clockStatus", "Clock Sync Status",
                "<span id=\"status-clock-syncstatus\">sync disabled</span>");
    }

    @Test
    public void formatSyncStateMapsSyncedToSyncedLiteral() {
        givenSyncState(ClockSyncState.SYNCED);

        whenFormatSyncStateIsCalled();

        thenResultIs("synced");
    }

    @Test
    public void formatSyncStateMapsNotSyncedToNotSyncedLiteral() {
        givenSyncState(ClockSyncState.NOT_SYNCED);

        whenFormatSyncStateIsCalled();

        thenResultIs("not synced");
    }

    @Test
    public void formatSyncStateMapsUnknownToUnknownLiteral() {
        givenSyncState(ClockSyncState.UNKNOWN);

        whenFormatSyncStateIsCalled();

        thenResultIs("unknown");
    }

    /*
     * Given
     */

    private void givenEpochMillis(String isoInstant) {
        this.epochMillis = Instant.parse(isoInstant).toEpochMilli();
    }

    private void givenZone(String zoneId) {
        this.zone = ZoneId.of(zoneId);
    }

    private void givenClockServiceReturning(Date date) {
        this.clockService = () -> date;
    }

    private void givenClockServiceThrowing() {
        this.clockService = () -> {
            throw new KuraException(KuraErrorCode.UNAVAILABLE_DEVICE);
        };
    }

    private void givenClockServiceReturningSyncStatus(ClockSyncState state, String syncProvider) {
        this.clockService = new ClockService() {

            @Override
            public Date getLastSync() {
                return null;
            }

            @Override
            public ClockSyncStatus getSyncStatus() {
                return new ClockSyncStatus(state, null, syncProvider);
            }
        };
    }

    private void givenClockServiceSyncStatusThrowing() {
        this.clockService = new ClockService() {

            @Override
            public Date getLastSync() {
                return null;
            }

            @Override
            public ClockSyncStatus getSyncStatus() throws KuraException {
                throw new KuraException(KuraErrorCode.UNAVAILABLE_DEVICE);
            }
        };
    }

    private void givenSyncState(ClockSyncState state) {
        this.syncState = state;
    }

    /*
     * When
     */

    private void whenFormatDateTimeIsCalled() {
        this.result = GwtStatusServiceImpl.formatDateTime(this.epochMillis, this.zone);
    }

    private void whenFormatLastSyncIsCalled() {
        this.result = GwtStatusServiceImpl.formatLastSync(this.clockService, this.zone);
    }

    private void whenAddSyncHealthRowsIsCalled() {
        this.pairs = new ArrayList<>();
        GwtStatusServiceImpl.addSyncHealthRows(this.pairs, this.clockService);
    }

    private void whenFormatSyncStateIsCalled() {
        this.result = GwtStatusServiceImpl.formatSyncState(this.syncState);
    }

    /*
     * Then
     */

    private void thenResultIs(String expected) {
        assertEquals(expected, this.result);
    }

    private void thenPairsCountIs(int expectedCount) {
        assertEquals(expectedCount, this.pairs.size());
    }

    private void thenPairHasGroupNameValue(int index, String expectedGroup, String expectedName,
            String expectedValue) {
        GwtGroupedNVPair pair = this.pairs.get(index);
        assertEquals(expectedGroup, pair.getGroup());
        assertEquals(expectedName, pair.getName());
        assertEquals(expectedValue, pair.getValue());
    }
}
