/*******************************************************************************
 * Copyright (c) 2011, 2026 Eurotech and/or its affiliates and others
 * 
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 * 
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.web.shared.model;

import java.io.Serializable;

public class GwtCommandResponse implements Serializable {

    private static final long serialVersionUID = -6187902237651876015L;

    private String command;
    private String stdout;
    private int exitValue;

    public GwtCommandResponse() {
    }

    public String getCommand() {
        return this.command;
    }

    public void setCommand(String command) {
        this.command = command;
    }

    public String getStdout() {
        return this.stdout;
    }

    public void setStdout(String stdout) {
        this.stdout = stdout;
    }

    public int getExitValue() {
        return this.exitValue;
    }

    public void setExitValue(int value) {
        this.exitValue = value;
    }
}
