/*******************************************************************************
 * Copyright (c) 2011, 2026 Eurotech and/or its affiliates and others
 * 
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 * 
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.web.shared.model;

import java.io.Serializable;

public class GwtSession extends GwtBaseModel implements Serializable {

    private static final long serialVersionUID = -2507268464782812398L;

    private boolean netAdminAvailable;
    private String kuraVersion;
    private String osVersion;
    private boolean developMode;

    public GwtSession() {
        this.netAdminAvailable = true;
        this.kuraVersion = "version-unknown";
    }

    public boolean isNetAdminAvailable() {
        return this.netAdminAvailable;
    }

    public void setNetAdminAvailable(boolean haveNetAdmin) {
        this.netAdminAvailable = haveNetAdmin;
    }

    public String getKuraVersion() {
        return this.kuraVersion;
    }

    public void setKuraVersion(String kuraVersion) {
        this.kuraVersion = kuraVersion;
    }

    public String getOsVersion() {
        return this.osVersion;
    }

    public void setOsVersion(String osVersion) {
        this.osVersion = osVersion;
    }

    public boolean isDevelopMode() {
        return this.developMode;
    }

    public void setDevelopMode(boolean developMode) {
        this.developMode = developMode;
    }
}
