/*******************************************************************************
 * Copyright (c) 2011, 2026 Eurotech and/or its affiliates and others
 * 
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 * 
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.web.shared.model;

import java.util.Map;

public class GwtWifiNetInterfaceConfig extends GwtNetInterfaceConfig {

    private static final long serialVersionUID = -7509149975400963837L;

    private GwtWifiConfig adhocWifiConfig;
    private GwtWifiConfig stationWifiConfig;
    private GwtWifiConfig accessPointWifiConfig;

    public GwtWifiNetInterfaceConfig() {
        super();

        this.adhocWifiConfig = new GwtWifiConfig();
        this.stationWifiConfig = new GwtWifiConfig();
        this.accessPointWifiConfig = new GwtWifiConfig();

        setWirelessMode(GwtWifiWirelessMode.netWifiWirelessModeStation.name());
    }

    public GwtWifiNetInterfaceConfig(GwtWifiConfig adhocConfig, GwtWifiConfig stationConfig,
            GwtWifiConfig accessPointConfig) {
        super();

        this.adhocWifiConfig = adhocConfig;
        this.stationWifiConfig = stationConfig;
        this.accessPointWifiConfig = accessPointConfig;

        setWirelessMode(GwtWifiWirelessMode.netWifiWirelessModeStation.name());
    }

    public void setAdhocWifiConfig(GwtWifiConfig adhocConfig) {
        this.adhocWifiConfig = adhocConfig;
    }

    public void setAdhocWifiConfig(Map<String, Object> properties) {
        this.adhocWifiConfig = new GwtWifiConfig();
        this.adhocWifiConfig.setProperties(properties);
    }

    public GwtWifiConfig getAdhocWifiConfig() {
        return this.adhocWifiConfig;
    }

    public Map<String, Object> getAdhocWifiConfigProps() {
        return this.adhocWifiConfig.getProperties();
    }

    public void setStationWifiConfig(GwtWifiConfig stationConfig) {
        this.stationWifiConfig = stationConfig;
    }

    public void setStationWifiConfig(Map<String, Object> properties) {
        this.stationWifiConfig = new GwtWifiConfig();
        this.stationWifiConfig.setProperties(properties);
    }

    public GwtWifiConfig getStationWifiConfig() {
        return this.stationWifiConfig;
    }

    public Map<String, Object> getStationWifiConfigProps() {

        return this.stationWifiConfig.getProperties();
    }

    public void setAccessPointWifiConfig(GwtWifiConfig accessPointConfig) {
        this.accessPointWifiConfig = accessPointConfig;
    }

    public void setAccessPointWifiConfig(Map<String, Object> properties) {
        this.accessPointWifiConfig = new GwtWifiConfig();
        this.accessPointWifiConfig.setProperties(properties);
    }

    public GwtWifiConfig getAccessPointWifiConfig() {
        return this.accessPointWifiConfig;
    }

    public Map<String, Object> getAccessPointWifiConfigProps() {

        return this.accessPointWifiConfig.getProperties();
    }

    public void setWifiConfig(GwtWifiConfig wifiConfig) {
        GwtWifiWirelessMode wifiMode = wifiConfig.getWirelessModeEnum();

        if (wifiMode.equals(GwtWifiWirelessMode.netWifiWirelessModeAccessPoint)) {
            setAccessPointWifiConfig(wifiConfig);
        } else if (wifiMode.equals(GwtWifiWirelessMode.netWifiWirelessModeAdHoc)) {
            setAdhocWifiConfig(wifiConfig);
        } else if (wifiMode.equals(GwtWifiWirelessMode.netWifiWirelessModeStation)) {
            setStationWifiConfig(wifiConfig);
        }
    }

    public GwtWifiConfig getActiveWifiConfig() {
        GwtWifiWirelessMode wifiMode = getWirelessModeEnum();
        GwtWifiConfig activeConfig = new GwtWifiConfig();
        activeConfig.setWirelessMode(wifiMode.name());

        if (wifiMode.equals(GwtWifiWirelessMode.netWifiWirelessModeAccessPoint)) {
            activeConfig = this.accessPointWifiConfig;
        } else if (wifiMode.equals(GwtWifiWirelessMode.netWifiWirelessModeAdHoc)) {
            activeConfig = this.adhocWifiConfig;
        } else if (wifiMode.equals(GwtWifiWirelessMode.netWifiWirelessModeStation)) {
            activeConfig = this.stationWifiConfig;
        }

        return activeConfig;
    }

    public void setWirelessMode(String wirelessMode) {
        set("wirelessMode", wirelessMode);
    }

    public String getWirelessMode() {
        return get("wirelessMode");
    }

    public GwtWifiWirelessMode getWirelessModeEnum() {
        return GwtWifiWirelessMode.valueOf(getWirelessMode());
    }

    @Override
    public boolean equals(Object o) {
        if (!(o instanceof GwtWifiNetInterfaceConfig other)) {
            return false;
        }

        if (super.equals(o) == false) {
            return false;
        }

        if (compare(getActiveWifiConfig(), other.getActiveWifiConfig()) == false) {
            return false;
        }

        return true;
    }

    private boolean compare(Object obj1, Object obj2) {
        if (obj1 == null) {
            if (obj2 != null) {
                return false;
            }
        } else {
            return obj1.equals(obj2);
        }

        return true;
    }
}
