/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.web.shared;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

import org.junit.Test;

public class ScaleOffsetTypeTest {

    private String input;
    private ScaleOffsetType result;
    private IllegalArgumentException thrown;

    @Test
    public void convertsDefinedByValueTypeByExactName() {
        givenInput("DEFINED_BY_VALUE_TYPE");

        whenGetScaleOffsetTypeIsCalled();

        thenResultIs(ScaleOffsetType.DEFINED_BY_VALUE_TYPE);
    }

    @Test
    public void convertsFloatByExactName() {
        givenInput("FLOAT");

        whenGetScaleOffsetTypeIsCalled();

        thenResultIs(ScaleOffsetType.FLOAT);
    }

    @Test
    public void convertsDoubleByExactName() {
        givenInput("DOUBLE");

        whenGetScaleOffsetTypeIsCalled();

        thenResultIs(ScaleOffsetType.DOUBLE);
    }

    @Test
    public void convertsIntegerByExactName() {
        givenInput("INTEGER");

        whenGetScaleOffsetTypeIsCalled();

        thenResultIs(ScaleOffsetType.INTEGER);
    }

    @Test
    public void convertsLongByExactName() {
        givenInput("LONG");

        whenGetScaleOffsetTypeIsCalled();

        thenResultIs(ScaleOffsetType.LONG);
    }

    @Test
    public void convertsCaseInsensitively() {
        givenInput("float");

        whenGetScaleOffsetTypeIsCalled();

        thenResultIs(ScaleOffsetType.FLOAT);
    }

    @Test
    public void nullInputThrowsIllegalArgumentExceptionNamingScaleOffsetType() {
        givenInput(null);

        whenGetScaleOffsetTypeIsCalledExpectingFailure();

        thenThrownMessageContains("ScaleOffsetType");
    }

    @Test
    public void unknownStringThrowsIllegalArgumentExceptionNamingScaleOffsetType() {
        givenInput("garbage");

        whenGetScaleOffsetTypeIsCalledExpectingFailure();

        thenThrownMessageContains("ScaleOffsetType");
    }

    /*
     * Given
     */

    private void givenInput(String input) {
        this.input = input;
    }

    /*
     * When
     */

    private void whenGetScaleOffsetTypeIsCalled() {
        this.result = ScaleOffsetType.getScaleOffsetType(this.input);
    }

    private void whenGetScaleOffsetTypeIsCalledExpectingFailure() {
        try {
            ScaleOffsetType.getScaleOffsetType(this.input);
            fail("expected IllegalArgumentException for input [" + this.input + "]");
        } catch (IllegalArgumentException e) {
            this.thrown = e;
        }
    }

    /*
     * Then
     */

    private void thenResultIs(ScaleOffsetType expected) {
        assertEquals("converted ScaleOffsetType must match", expected, this.result);
    }

    private void thenThrownMessageContains(String expectedSubstring) {
        String message = this.thrown.getMessage();
        assertTrue("exception message must name [" + expectedSubstring + "] but was: [" + message + "]",
                message != null && message.contains(expectedSubstring));
    }
}
