/*******************************************************************************
 * Copyright (c) 2011, 2026 Eurotech and/or its affiliates and others
 * 
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 * 
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.web.client.ui.status;

import java.util.Collections;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import org.eclipse.kura.web.Console;
import org.eclipse.kura.web.client.messages.Messages;
import org.eclipse.kura.web.client.messages.ValidationMessages;
import org.eclipse.kura.web.client.ui.EntryClassUi;
import org.eclipse.kura.web.client.util.EventService;
import org.eclipse.kura.web.client.util.request.RequestQueue;
import org.eclipse.kura.web.shared.ForwardedEventTopic;
import org.eclipse.kura.web.shared.model.GwtGroupedNVPair;
import org.eclipse.kura.web.shared.model.GwtSession;
import org.eclipse.kura.web.shared.service.GwtSecurityTokenService;
import org.eclipse.kura.web.shared.service.GwtSecurityTokenServiceAsync;
import org.eclipse.kura.web.shared.service.GwtStatusService;
import org.eclipse.kura.web.shared.service.GwtStatusServiceAsync;
import org.gwtbootstrap3.client.ui.Button;
import org.gwtbootstrap3.client.ui.Well;
import org.gwtbootstrap3.client.ui.gwt.CellTable;

import com.google.gwt.cell.client.SafeHtmlCell;
import com.google.gwt.core.client.GWT;
import com.google.gwt.core.client.JavaScriptObject;
import com.google.gwt.core.client.JsonUtils;
import com.google.gwt.http.client.Request;
import com.google.gwt.http.client.RequestBuilder;
import com.google.gwt.http.client.RequestCallback;
import com.google.gwt.http.client.RequestException;
import com.google.gwt.http.client.Response;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.i18n.client.TimeZone;
import com.google.gwt.safehtml.shared.SafeHtml;
import com.google.gwt.safehtml.shared.SafeHtmlUtils;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.user.cellview.client.Column;
import com.google.gwt.user.cellview.client.TextColumn;
import com.google.gwt.user.client.Timer;
import com.google.gwt.user.client.ui.Composite;
import com.google.gwt.user.client.ui.Widget;
import com.google.gwt.view.client.ListDataProvider;

public class StatusPanelUi extends Composite {

    private static final Logger logger = Logger.getLogger(StatusPanelUi.class.getSimpleName());
    private static StatusPanelUiUiBinder uiBinder = GWT.create(StatusPanelUiUiBinder.class);

    interface StatusPanelUiUiBinder extends UiBinder<Widget, StatusPanelUi> {
    }

    private static final ValidationMessages msgs = GWT.create(ValidationMessages.class);
    private static final Messages MSG = GWT.create(Messages.class);

    private static final String CLOCK_GROUP = "clockStatus";
    private static final String CLOCK_ROW_NAME = "System Date/Time (YYYY-MM-DD)";
    private static final String CLOCK_SPAN_PREFIX = "<span id=\"status-clock-datetime\">";
    private static final String CLOCK_SPAN_SUFFIX = "</span>";
    private static final String CLOCK_ENDPOINT_URL = Console.ADMIN_ROOT + '/' + GWT.getModuleName() + "/clock";
    private static final int CLOCK_TICK_INTERVAL_MS = 1000;
    private static final int CLOCK_POLL_INTERVAL_MS = 2000;
    private static final DateTimeFormat CLOCK_DATE_FORMAT = DateTimeFormat.getFormat("yyyy-MM-dd HH:mm:ss");

    private final GwtStatusServiceAsync gwtStatusService = GWT.create(GwtStatusService.class);
    private final GwtSecurityTokenServiceAsync gwtXSRFService = GWT.create(GwtSecurityTokenService.class);

    private GwtSession currentSession;
    private final ListDataProvider<GwtGroupedNVPair> statusGridProvider = new ListDataProvider<>();
    private EntryClassUi parent;

    private Timer clockPollTimer;
    private Timer clockTickTimer;
    private Long clockSeedEpoch;
    private int clockSeedOffsetMillis;
    private String clockSeedZoneId;
    private long clockSeedBrowserMillis;

    @UiField
    Well statusWell;
    @UiField
    Button statusRefresh;
    @UiField
    CellTable<GwtGroupedNVPair> statusGrid = new CellTable<>();

    public StatusPanelUi() {
        logger.log(Level.FINER, "Initializing StatusPanelUi...");
        initWidget(uiBinder.createAndBindUi(this));
        // Set text for buttons
        this.statusRefresh.setText(MSG.refresh());

        this.statusGrid.setRowStyles((row, rowIndex) -> {
            if ("Cloud Services".equals(row.getName()) || "Connection Name".equals(row.getName())
                    || "Ethernet Settings".equals(row.getName()) || "Wireless Settings".equals(row.getName())
                    || "Cellular Settings".equals(row.getName()) || "Position Status".equals(row.getName())
                    || "Tamper Detection Status".equals(row.getName()) || "System Clock".equals(row.getName())
                    || "システムクロック".equals(row.getName())) {
                return "rowHeader";
            } else {
                return " ";
            }
        });

        loadStatusTable(this.statusGrid, this.statusGridProvider);

        this.statusRefresh.addClickHandler(e -> loadStatusData(true));

        EventService.Handler stateChangeHandler = eventInfo -> {
            if (StatusPanelUi.this.isVisible() && StatusPanelUi.this.isAttached()) {
                loadStatusData(false);
            }
        };

        EventService.subscribe(ForwardedEventTopic.CLOUD_CONNECTION_STATUS_ESTABLISHED, stateChangeHandler);
        EventService.subscribe(ForwardedEventTopic.CLOUD_CONNECTION_STATUS_LOST, stateChangeHandler);
        EventService.subscribe(ForwardedEventTopic.TAMPER_EVENT, stateChangeHandler);
        EventService.subscribe(ForwardedEventTopic.CLOCK_EVENT, stateChangeHandler);

    }

    @Override
    protected void onLoad() {
        super.onLoad();

        this.clockPollTimer = new Timer() {

            @Override
            public void run() {
                pollClock();
            }
        };
        this.clockPollTimer.run();
        this.clockPollTimer.scheduleRepeating(CLOCK_POLL_INTERVAL_MS);

        this.clockTickTimer = new Timer() {

            @Override
            public void run() {
                tickClock();
            }
        };
        this.clockTickTimer.scheduleRepeating(CLOCK_TICK_INTERVAL_MS);
    }

    @Override
    protected void onUnload() {
        if (this.clockPollTimer != null) {
            this.clockPollTimer.cancel();
            this.clockPollTimer = null;
        }
        if (this.clockTickTimer != null) {
            this.clockTickTimer.cancel();
            this.clockTickTimer = null;
        }
        // a stale seed must not resume ticking on re-show before a fresh poll lands
        this.clockSeedEpoch = null;

        super.onUnload();
    }

    private void pollClock() {
        if (!isVisible() || !isAttached()) {
            return;
        }

        RequestBuilder builder = new RequestBuilder(RequestBuilder.GET, CLOCK_ENDPOINT_URL);
        try {
            builder.sendRequest(null, new RequestCallback() {

                @Override
                public void onResponseReceived(Request request, Response response) {
                    if (response.getStatusCode() != Response.SC_OK) {
                        logger.fine("clock poll failed with HTTP status " + response.getStatusCode());
                        return;
                    }

                    ClockResponse clock = JsonUtils.safeEval(response.getText());
                    StatusPanelUi.this.clockSeedEpoch = (long) clock.getEpoch();
                    StatusPanelUi.this.clockSeedOffsetMillis = clock.getOffsetMillis();
                    StatusPanelUi.this.clockSeedZoneId = clock.getZoneId();
                    StatusPanelUi.this.clockSeedBrowserMillis = System.currentTimeMillis();
                }

                @Override
                public void onError(Request request, Throwable exception) {
                    logger.fine("clock poll error: " + exception.getMessage());
                }
            });
        } catch (RequestException e) {
            logger.fine("clock poll request failed: " + e.getMessage());
        }
    }

    private void tickClock() {
        if (this.clockSeedEpoch == null || !isVisible() || !isAttached()) {
            return;
        }

        long displayedEpoch = this.clockSeedEpoch + (System.currentTimeMillis() - this.clockSeedBrowserMillis);
        updateClockRow(formatClockValue(displayedEpoch, this.clockSeedOffsetMillis, this.clockSeedZoneId));
    }

    private static String formatClockValue(long epochMillis, int offsetMillis, String zoneId) {
        // the negation is required: offsetMillis is positive east of UTC (java.time convention),
        // while GWT's TimeZone.createTimeZone takes minutes WEST of UTC (JS getTimezoneOffset convention)
        String datePart = CLOCK_DATE_FORMAT.format(new Date(epochMillis),
                TimeZone.createTimeZone(-(offsetMillis / 60000)));

        int totalOffsetMinutes = offsetMillis / 60000;
        String sign = totalOffsetMinutes < 0 ? "-" : "+";
        int absOffsetMinutes = Math.abs(totalOffsetMinutes);
        String offset = sign + pad2(absOffsetMinutes / 60) + ":" + pad2(absOffsetMinutes % 60);

        return CLOCK_SPAN_PREFIX + datePart + " (UTC" + offset + ", " + zoneId + ")" + CLOCK_SPAN_SUFFIX;
    }

    private static String pad2(int value) {
        return value < 10 ? "0" + value : String.valueOf(value);
    }

    private void updateClockRow(String wrappedHtml) {
        List<GwtGroupedNVPair> list = this.statusGridProvider.getList();
        for (int i = 0; i < list.size(); i++) {
            GwtGroupedNVPair pair = list.get(i);
            if (CLOCK_GROUP.equals(pair.getGroup()) && CLOCK_ROW_NAME.equals(pair.getName())) {
                pair.setValue(wrappedHtml);
                this.statusGrid.setRowData(i, Collections.singletonList(pair));
                return;
            }
        }
    }

    private static final class ClockResponse extends JavaScriptObject {

        protected ClockResponse() {
        }

        native double getEpoch()
        /*-{
            return this.epoch;
        }-*/;

        native int getOffsetMillis()
        /*-{
            return this.offsetMillis;
        }-*/;

        native String getZoneId()
        /*-{
            return this.zoneId;
        }-*/;
    }

    // get current session from UI parent
    public void setSession(GwtSession gwtBSSession) {
        this.currentSession = gwtBSSession;
    }

    // create table layout
    public void loadStatusTable(CellTable<GwtGroupedNVPair> grid, ListDataProvider<GwtGroupedNVPair> dataProvider) {
        TextColumn<GwtGroupedNVPair> col1 = new TextColumn<GwtGroupedNVPair>() {

            @Override
            public String getValue(GwtGroupedNVPair object) {
                return String.valueOf(object.getName());
            }
        };
        col1.setCellStyleNames("status-table-row");
        grid.addColumn(col1);

        Column<GwtGroupedNVPair, SafeHtml> col2 = new Column<GwtGroupedNVPair, SafeHtml>(new SafeHtmlCell()) {

            @Override
            public SafeHtml getValue(GwtGroupedNVPair object) {
                return SafeHtmlUtils.fromTrustedString(String.valueOf(object.getValue()));
            }
        };

        col2.setCellStyleNames("status-table-row");
        grid.addColumn(col2);
        dataProvider.addDataDisplay(grid);
    }

    // fetch table data
    public void loadStatusData(boolean recompute) {
        this.statusGridProvider.getList().clear();
        RequestQueue.submit(c -> this.gwtXSRFService
                .generateSecurityToken(c.callback(token -> StatusPanelUi.this.gwtStatusService.getDeviceConfig(token,
                        StatusPanelUi.this.currentSession.isNetAdminAvailable(), recompute, c.callback(result -> {
                            String title = "cloudStatus";
                            StatusPanelUi.this.statusGridProvider.getList()
                                    .add(new GwtGroupedNVPair(" ", msgs.getString(title), " "));

                            Iterator<GwtGroupedNVPair> it = result.iterator();
                            while (it.hasNext()) {
                                GwtGroupedNVPair connectionName = it.next();
                                if (!title.equals(connectionName.getGroup())) {
                                    title = connectionName.getGroup();
                                    StatusPanelUi.this.statusGridProvider.getList()
                                            .add(new GwtGroupedNVPair(" ", msgs.getString(title), " "));
                                }
                                StatusPanelUi.this.statusGridProvider.getList().add(connectionName);
                            }
                            int size = StatusPanelUi.this.statusGridProvider.getList().size();
                            StatusPanelUi.this.statusGrid.setVisibleRange(0, size);
                            StatusPanelUi.this.statusGridProvider.flush();
                        })))));
    }

    public void setParent(EntryClassUi parent) {
        this.parent = parent;
    }
}