/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.web.server.util;

import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;

import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

import org.eclipse.kura.configuration.Password;
import org.eclipse.kura.core.configuration.ComponentConfigurationImpl;
import org.eclipse.kura.web.shared.model.GwtConfigComponent;
import org.eclipse.kura.web.shared.model.GwtConfigParameter;
import org.eclipse.kura.web.shared.model.GwtConfigParameter.GwtConfigParameterType;
import org.junit.Test;

public class GwtServerUtilPasswordTest {

    private static final String PASSWORD = "password";
    private static final String PASSWORD_UPPERCASE = "Password";
    private GwtConfigParameter passwordParam;
    private Object currentObjValue;
    private Object result;

    private GwtConfigComponent gwtConfig;
    private ComponentConfigurationImpl currentCC;
    private Map<String, Object> fillResult;

    @Test
    public void placeholderWithNullCurrentValueAndNotRequiredReturnsNull() {
        givenPasswordParam(PASSWORD, false, null);
        givenParamValue(GwtServerUtil.PASSWORD_PLACEHOLDER);
        givenCurrentObjValue(null);

        whenGetUserDefinedObjectIsCalled();

        thenResultIsNull();
    }

    @Test
    public void placeholderWithExistingPasswordCurrentValuePreservesIt() {
        givenPasswordParam(PASSWORD, false, null);
        givenParamValue(GwtServerUtil.PASSWORD_PLACEHOLDER);
        givenCurrentObjValue(new Password("secret"));

        whenGetUserDefinedObjectIsCalled();

        thenResultIsPasswordWithValue("secret");
    }

    @Test
    public void placeholderWithEmptyPasswordCurrentValuePreservesEmptyPassword() {
        givenPasswordParam(PASSWORD, false, null);
        givenParamValue(GwtServerUtil.PASSWORD_PLACEHOLDER);
        givenCurrentObjValue(new Password(""));

        whenGetUserDefinedObjectIsCalled();

        thenResultIsEmptyPassword();
    }

    @Test
    public void placeholderWithNullCurrentValueAndRequiredIgnoresDefaultReturnsNull() {
        givenPasswordParam(PASSWORD, true, "defaultpass");
        givenParamValue(GwtServerUtil.PASSWORD_PLACEHOLDER);
        givenCurrentObjValue(null);

        whenGetUserDefinedObjectIsCalled();

        thenResultIsNull();
    }

    @Test
    public void placeholderWithNullCurrentValueAndRequiredButNoDefaultReturnsNull() {
        givenPasswordParam(PASSWORD, true, null);
        givenParamValue(GwtServerUtil.PASSWORD_PLACEHOLDER);
        givenCurrentObjValue(null);

        whenGetUserDefinedObjectIsCalled();

        thenResultIsNull();
    }

    @Test
    public void nonPlaceholderPasswordValueIsUsedDirectly() {
        givenPasswordParam(PASSWORD, false, null);
        givenParamValue("newpassword");
        givenCurrentObjValue(null);

        whenGetUserDefinedObjectIsCalled();

        thenResultIsPasswordWithValue("newpassword");
    }

    @Test
    public void fillPropertiesUsesNameForPasswordLookup() {
        givenGwtConfigWithPasswordParam(PASSWORD, PASSWORD_UPPERCASE);
        givenCurrentCCWithPassword(PASSWORD_UPPERCASE, new Password("stored"));

        whenFillPropertiesFromConfigurationIsCalled();

        thenFillResultPasswordHasValue(PASSWORD, "stored");
    }

    @Test
    public void fillPropertiesWithNullCurrentCCOmitsPasswordForPlaceholder() {
        givenGwtConfigWithPasswordParam(PASSWORD, PASSWORD_UPPERCASE);

        whenFillPropertiesFromConfigurationWithNullCCIsCalled();

        thenFillResultHasNoPasswordEntry(PASSWORD);
    }

    /*
     * Given
     */

    private void givenPasswordParam(String id, boolean required, String defaultValue) {
        this.passwordParam = new GwtConfigParameter();
        this.passwordParam.setId(id);
        this.passwordParam.setName(id.substring(0, 1).toUpperCase() + id.substring(1));
        this.passwordParam.setType(GwtConfigParameterType.PASSWORD);
        this.passwordParam.setRequired(required);
        this.passwordParam.setCardinality(0);
        if (defaultValue != null) {
            this.passwordParam.setDefault(defaultValue);
        }
    }

    private void givenParamValue(String value) {
        this.passwordParam.setValue(value);
    }

    private void givenCurrentObjValue(Object value) {
        this.currentObjValue = value;
    }

    private void givenGwtConfigWithPasswordParam(String id, String name) {
        this.gwtConfig = new GwtConfigComponent();
        this.gwtConfig.setComponentId("test.pid");

        GwtConfigParameter param = new GwtConfigParameter();
        param.setId(id);
        param.setName(name);
        param.setType(GwtConfigParameterType.PASSWORD);
        param.setRequired(false);
        param.setCardinality(0);
        param.setValue(GwtServerUtil.PASSWORD_PLACEHOLDER);

        this.gwtConfig.setParameters(Arrays.asList(param));
    }

    private void givenCurrentCCWithPassword(String key, Password value) {
        Map<String, Object> props = new HashMap<>();
        props.put(key, value);
        this.currentCC = new ComponentConfigurationImpl("test.pid", null, props);
    }

    /*
     * When
     */

    private void whenGetUserDefinedObjectIsCalled() {
        this.result = GwtServerUtil.getUserDefinedObject(this.passwordParam, this.currentObjValue);
    }

    private void whenFillPropertiesFromConfigurationIsCalled() {
        this.fillResult = GwtServerUtil.fillPropertiesFromConfiguration(this.gwtConfig, this.currentCC);
    }

    private void whenFillPropertiesFromConfigurationWithNullCCIsCalled() {
        this.fillResult = GwtServerUtil.fillPropertiesFromConfiguration(this.gwtConfig, null);
    }

    /*
     * Then
     */

    private void thenResultIsEmptyPassword() {
        assertNotNull("result must not be null", this.result);
        assertArrayEquals("password must be empty", new char[0], ((Password) this.result).getPassword());
    }

    private void thenResultIsNull() {
        assertNull("result must be null", this.result);
    }

    private void thenResultIsPasswordWithValue(String expected) {
        assertNotNull("result must not be null", this.result);
        assertArrayEquals("password value mismatch", expected.toCharArray(), ((Password) this.result).getPassword());
    }

    private void thenFillResultHasNoPasswordEntry(String key) {
        assertNotNull("fill result must not be null", this.fillResult);
        assertFalse("password entry must not be present", this.fillResult.containsKey(key));
    }

    private void thenFillResultPasswordHasValue(String key, String expected) {
        assertNotNull("fill result must not be null", this.fillResult);
        Object value = this.fillResult.get(key);
        assertNotNull("password entry must be present", value);
        assertArrayEquals("password value mismatch", expected.toCharArray(), ((Password) value).getPassword());
    }
}
